# Bài 3.1

In [2]:
import numpy as np

np.__version__

'2.3.4'

In [3]:
np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35217",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0fv2o5t8/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib directo

# Bài 3.2

In [5]:
import numpy as np

arr =np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#ptu lẻ
arr_odd = arr[arr % 2 != 0]
arr_odd


array([1, 3, 5, 7, 9])

In [ ]:
#ptu chẵn
arr_even = arr[arr % 2 == 0]
arr_even


array([0, 2, 4, 6, 8])

In [ ]:
# Chẵn giữ nguyên, lẻ thành 100
arr_update1 = np.where(arr % 2 == 0, arr, 100)
arr_update1

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

# Bài 3.3

In [ ]:
import numpy as np

arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [14]:
#lấy ptu xuất hiện ở cả a và b
arr_c = np.intersect1d(arr_a, arr_b)
arr_c

array([2, 4])

In [15]:
#lấy phần tử chỉ có trong a (không có trong b)
arr_d = np.setdiff1d(arr_a, arr_b)
arr_d

array([1, 3, 5, 6])

In [16]:
# Tạo arr_e và lọc các phần tử từ 5–10
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
arr_f

array([ 6,  9, 10,  8,  6])

# Bài 3.4

In [17]:
import numpy as np

# Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1
arr_zeros

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [18]:
# Tạo arr_h từ 10 đến 24, đảo ngược thứ tự
arr_h = np.arange(10, 25)
arr_h = arr_h[::-1]
arr_h

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [19]:
# Cho arr_k, tạo arr_l với phần tử khác 0
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
arr_l


array([1, 2, 8, 2, 1, 3, 5])

In [20]:
# Thêm 2 phần tử 10 và 20 vào cuối mảng arr_l
arr_l = np.append(arr_l, [10, 20])
arr_l


array([ 1,  2,  8,  2,  1,  3,  5, 10, 20])

In [21]:
# Chèn 100 vào vị trí thứ 5 (index = 5)
arr_l = np.insert(arr_l, 5, 100)
arr_l

array([  1,   2,   8,   2,   1, 100,   3,   5,  10,  20])

In [22]:
# Xóa phần tử ở vị trí thứ 3
arr_l = np.delete(arr_l, 3)
arr_l


array([  1,   2,   8,   1, 100,   3,   5,  10,  20])

# Bài 3.5

In [23]:
import numpy as np

np.random.seed(0)
arr_height = np.random.normal(70, 3, 200)  
arr_weight = np.random.normal(180, 20, 200) 

In [ ]:
#kiểm tra kích thước dữ liệu
print("Kích thước arr_height:", arr_height.shape)
print("Kích thước arr_weight:", arr_weight.shape)

Kích thước arr_height: (200,)
Kích thước arr_weight: (200,)


In [37]:
#quy đổi inch - mét (1 inch = 0.0254 m)
he_so_quy_doi_chieu_cao = 0.0254
arr_height_m = arr_height * he_so_quy_doi_chieu_cao
print("Chiều cao (m):", arr_height_m[:5]) 

Chiều cao (m): [1.91242079 1.80849198 1.85257983 1.94875606 1.92030792]


In [ ]:
#quy đổi pound - kg (1 pound = 0.453592 kg)
he_so_quy_doi_can_nang = 0.453592
arr_weight_kg = arr_weight * he_so_quy_doi_can_nang
print("Cân nặng (kg):", arr_weight_kg[:5])

Cân nặng (kg): [78.29740144 79.4749504  91.62249591 87.59100772 87.45373078]


In [ ]:
#tính BMI = cân nặng / (chiều cao^2)
arr_bmi = arr_weight_kg / (arr_height_m ** 2)
print("Chỉ số BMI (5 người đầu tiên):", arr_bmi[:5])


Chỉ số BMI (5 người đầu tiên): [21.40821397 24.29948625 26.69612662 23.06452764 23.71573537]


In [ ]:
#giá trị cân nặng ở vị trí index = 50
print("Cân nặng cầu thủ thứ 51 (index 50):", arr_weight_kg[50])

Cân nặng cầu thủ thứ 51 (index 50): 86.3735771887992


In [ ]:
#lấy chiều cao từ index 100 đến 110 (bao gồm 110)
arr_height_m_100 = arr_height_m[100:111]
print("Chiều cao từ index 100 đến 110:", arr_height_m_100)


Chiều cao từ index 100 đến 110: [1.92149608 1.67530076 1.68118904 1.85186803 1.688608   1.92610393
 1.74648223 1.72104394 1.92452818 1.89081523 1.92030799]


In [ ]:
#lọc cầu thủ có BMI < 21
bmi_duoi_21 = arr_bmi[arr_bmi < 21]
print("Số cầu thủ có BMI < 21:", len(bmi_duoi_21))
print("Các giá trị BMI < 21:", bmi_duoi_21)

Số cầu thủ có BMI < 21: 17
Các giá trị BMI < 21: [17.77842028 17.98548858 19.96574914 17.67465471 20.54460225 20.68475085
 20.99114583 18.90335182 20.88128449 20.27494648 20.83440166 19.22984723
 19.79766831 20.22038445 18.83362377 18.6896179  20.46788571]


In [ ]:
#chiều cao và cân nặng trung bình
chieu_cao_tb = np.mean(arr_height_m)
can_nang_tb = np.mean(arr_weight_kg)
print("\nChiều cao trung bình: {:.2f} m".format(chieu_cao_tb))
print("Cân nặng trung bình: {:.2f} kg".format(can_nang_tb))


Chiều cao trung bình: 1.78 m
Cân nặng trung bình: 80.49 kg


In [ ]:
#chiều cao và cân nặng lớn nhất
chieu_cao_max = np.max(arr_height_m)
can_nang_max = np.max(arr_weight_kg)
print("Chiều cao lớn nhất: {:.2f} m".format(chieu_cao_max))
print("Cân nặng lớn nhất: {:.2f} kg".format(can_nang_max))


Chiều cao lớn nhất: 1.96 m
Cân nặng lớn nhất: 102.55 kg


In [ ]:
#chiều cao và cân nặng nhỏ nhất
chieu_cao_min = np.min(arr_height_m)
can_nang_min = np.min(arr_weight_kg)
print("Chiều cao nhỏ nhất: {:.2f} m".format(chieu_cao_min))
print("Cân nặng nhỏ nhất: {:.2f} kg".format(can_nang_min))

Chiều cao nhỏ nhất: 1.58 m
Cân nặng nhỏ nhất: 56.49 kg


# Bài 3.6

In [ ]:
import numpy as np

#tạo array 3x3 vs các giá trị True
arr = np.full((3, 3), True, dtype=bool)
print("Mảng arr 3x3 toàn giá trị True:", arr)

Mảng arr 3x3 toàn giá trị True: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [40]:
#tạo arr_1D và chuyển thành arr_2D 3x3
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
print("Mảng arr_2D ban đầu:", arr_2D)

Mảng arr_2D ban đầu: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
#đổi cột 1 sang 3 và ngược lại bắt đầu từ 0
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("Sau khi hoán đổi cột 1 và cột 3:", arr_2D)

Sau khi hoán đổi cột 1 và cột 3: [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [42]:
#hoán đổi dòng 1 và dòng 2
arr_2D[[0, 1]] = arr_2D[[1, 0]]
print("Sau khi hoán đổi dòng 1 và dòng 2:", arr_2D)

Sau khi hoán đổi dòng 1 và dòng 2: [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [44]:
#đảo ngược các dòng, hàng
arr_2D = arr_2D[::-1, :]
print("Sau khi đảo ngược thứ tự các dòng:", arr_2D)

Sau khi đảo ngược thứ tự các dòng: [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [45]:
#đảo ngược các cột
arr_2D = arr_2D[:, ::-1]
print("Sau khi đảo ngược thứ tự các cột:", arr_2D)

Sau khi đảo ngược thứ tự các cột: [[3 4 5]
 [0 1 2]
 [6 7 8]]


# Bài 3.7

In [51]:
import numpy as np

baseball = [
    [74, 180],
    [72, 215],
    [73, 210],
    [69, 185],
    [70, 190],
    [76, 215],
    [71, 200],
    [73, 188],
    [75, 220],
    [77, 230]
]


In [52]:
#tạo NumPy array từ list
np_baseball = np.array(baseball)
print("Mảng np_baseball:", np_baseball)

Mảng np_baseball: [[ 74 180]
 [ 72 215]
 [ 73 210]
 [ 69 185]
 [ 70 190]
 [ 76 215]
 [ 71 200]
 [ 73 188]
 [ 75 220]
 [ 77 230]]


In [ ]:
# kiểu dữ liệu và kích thước
print("Kiểu dữ liệu của np_baseball:", np_baseball.dtype)
print("Kích thước mảng (shape):", np_baseball.shape)

Kiểu dữ liệu của np_baseball: int64
Kích thước mảng (shape): (10, 2)


In [ ]:
# in các giá trị dòng thứ 50
print("Dòng thứ 5 (minh họa cho dòng 50):", np_baseball[4])

Dòng thứ 5 (minh họa cho dòng 50): [ 70 190]


In [55]:
#tạo np_weight từ cột 2 (cột cân nặng)
np_weight = np_baseball[:, 1]
print("Mảng np_weight (cột cân nặng):", np_weight)

Mảng np_weight (cột cân nặng): [180 215 210 185 190 215 200 188 220 230]


In [56]:
#chiều cao của vận động viên thứ 124
print("Chiều cao vận động viên thứ 4 (minh họa):", np_baseball[3, 0], "inch")

Chiều cao vận động viên thứ 4 (minh họa): 69 inch


In [57]:
#tính chiều cao & cân nặng trung bình
chieu_cao_tb = np.mean(np_baseball[:, 0])
can_nang_tb = np.mean(np_baseball[:, 1])
print("Chiều cao trung bình: {:.2f} inch".format(chieu_cao_tb))
print("Cân nặng trung bình: {:.2f} pounds".format(can_nang_tb))

Chiều cao trung bình: 73.00 inch
Cân nặng trung bình: 203.30 pounds


In [58]:
#phân tích mối tương quan giữa chiều cao, cân nặng
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("Hệ số tương quan giữa chiều cao và cân nặng:", round(corr, 3))

if corr > 0.5:
    print("Có tương quan thuận (chiều cao tăng - cân nặng tăng).")
elif corr < -0.5:
    print("Có tương quan nghịch (chiều cao tăng - cân nặng giảm).")
else:
    print("Không có tương quan rõ ràng giữa chiều cao và cân nặng.")

Hệ số tương quan giữa chiều cao và cân nặng: 0.657
Có tương quan thuận (chiều cao tăng - cân nặng tăng).


# Bài 3.8

In [61]:
import numpy as np

heights = [183, 175, 190, 178, 181, 188, 177, 172, 195, 180]
positions = ['GK', 'D', 'A', 'M', 'D', 'A', 'GK', 'M', 'D', 'A']

In [62]:
#tạo numpy array từ list

# a) Tạo np_positions
np_positions = np.array(positions)
print("Mảng np_positions:", np_positions)
print("Kiểu dữ liệu:", np_positions.dtype)

# b) Tạo np_heights
np_heights = np.array(heights)
print("Mảng np_heights:", np_heights)
print("Kiểu dữ liệu:", np_heights.dtype)

Mảng np_positions: ['GK' 'D' 'A' 'M' 'D' 'A' 'GK' 'M' 'D' 'A']
Kiểu dữ liệu: <U2
Mảng np_heights: [183 175 190 178 181 188 177 172 195 180]
Kiểu dữ liệu: int64


In [63]:
#tính chiều cao trung bình của các GK
mask_gk = np_positions == 'GK'
avg_gk = np.mean(np_heights[mask_gk])
print("Chiều cao trung bình của GK:", round(avg_gk, 2), "cm")

Chiều cao trung bình của GK: 180.0 cm


In [64]:
#tính chiều cao trung bình của những vị trí KHÔNG phải GK
mask_not_gk = np_positions != 'GK'
avg_not_gk = np.mean(np_heights[mask_not_gk])
print("Chiều cao trung bình của các vị trí khác GK:", round(avg_not_gk, 2), "cm")

Chiều cao trung bình của các vị trí khác GK: 182.38 cm


In [65]:
#tạo mảng dữ liệu có cấu trúc
players_dtype = np.dtype([('position', 'U5'), ('height', 'f8')])
players = np.array(list(zip(np_positions, np_heights)), dtype=players_dtype)
print("Mảng structured array players:", players)

Mảng structured array players: [('GK', 183.) ('D', 175.) ('A', 190.) ('M', 178.) ('D', 181.) ('A', 188.)
 ('GK', 177.) ('M', 172.) ('D', 195.) ('A', 180.)]


In [66]:
#sắp xếp mảng players theo chiều cao
players_sorted = np.sort(players, order='height')
print("Mảng players sau khi sắp xếp theo chiều cao:", players_sorted)

Mảng players sau khi sắp xếp theo chiều cao: [('M', 172.) ('D', 175.) ('GK', 177.) ('M', 178.) ('A', 180.) ('D', 181.)
 ('GK', 183.) ('A', 188.) ('A', 190.) ('D', 195.)]


In [68]:
#cầu thủ cao nhất và thấp nhất
tallest = players_sorted[-1]
shortest = players_sorted[0]
print("Vị trí có chiều cao cao nhất: {} ({:.2f} cm)".format(tallest['position'], tallest['height']))
print("Vị trí có chiều cao thấp nhất: {} ({:.2f} cm)".format(shortest['position'], shortest['height']))

Vị trí có chiều cao cao nhất: D (195.00 cm)
Vị trí có chiều cao thấp nhất: M (172.00 cm)


# Bài 3.9

In [16]:
import pandas as pd
data = {
    'Team': ['England', 'France', 'Germany', 'Italy', 'Portugal', 'Spain', 'Greece', 'Russia', 'Croatia', 'Ireland'],
    'Goals': [5, 3, 10, 6, 7, 12, 5, 4, 4, 1],
    'Shooting Accuracy': ['45%', '41%', '52%', '43%', '47%', '55%', '36%', '39%', '42%', '33%'],
    'Yellow Cards': [5, 6, 7, 16, 12, 11, 9, 6, 9, 14],
    'Red Cards': [0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
}

euro12_df = pd.DataFrame(data)
euro12_df.to_csv('euro2012.csv', index=False, encoding='utf-8')
print("Đã tạo file euro2012.csv thành công!")


Đã tạo file euro2012.csv thành công!


In [17]:
euro12 = pd.read_csv('euro2012.csv')
print("giá trị cột Goals:")
print(euro12['Goals'])

giá trị cột Goals:
0     5
1     3
2    10
3     6
4     7
5    12
6     5
7     4
8     4
9     1
Name: Goals, dtype: int64


In [18]:
# có bao nhiêu đội tham gia Euro 2012
num_teams = euro12.shape[0]
num_teams

10

In [19]:
# in thông tin của Euro2012 
print("Thông tin DataFrame euro12:")
euro12.info()

Thông tin DataFrame euro12:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Team               10 non-null     object
 1   Goals              10 non-null     int64 
 2   Shooting Accuracy  10 non-null     object
 3   Yellow Cards       10 non-null     int64 
 4   Red Cards          10 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes


In [20]:
#tạo 1 data frame mới từ euro12 có tên là discipline
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print("ataFrame discipline:")
print(discipline.head())

ataFrame discipline:
       Team  Yellow Cards  Red Cards
0   England             5          0
1    France             6          0
2   Germany             7          0
3     Italy            16          0
4  Portugal            12          0


In [21]:
#sx discipline giảm dần theo 2 cột 
discipline_sorted = discipline.sort_values(
    by=['Red Cards', 'Yellow Cards'], 
    ascending=False
)
print("DataFrame discipline đã sắp xếp:")
print(discipline_sorted)

DataFrame discipline đã sắp xếp:
       Team  Yellow Cards  Red Cards
9   Ireland            14          1
6    Greece             9          1
3     Italy            16          0
4  Portugal            12          0
5     Spain            11          0
8   Croatia             9          0
2   Germany             7          0
1    France             6          0
7    Russia             6          0
0   England             5          0


In [22]:
# a) Tính trung bình Yellow Cards
yellow_cards_mean = euro12['Yellow Cards'].to_numpy().mean() 
print(f"trung bình Yellow Cards: {yellow_cards_mean:.2f}")
# b) Lọc các đội đã ghi hơn 6 bàn thắng
mask_goals = euro12['Goals'] > 6
teams_over_6_goals = euro12[mask_goals]
print("các đội đã ghi hơn 6 bàn thắng:")
print(teams_over_6_goals[['Team', 'Goals']])

trung bình Yellow Cards: 9.50
các đội đã ghi hơn 6 bàn thắng:
       Team  Goals
2   Germany     10
4  Portugal      7
5     Spain     12


In [23]:
# in 7 cột đầu của euro12
cols_7_first = euro12.iloc[:, :7]
print("7 cột đầu của euro12:")
print(cols_7_first.head(3))

7 cột đầu của euro12:
      Team  Goals Shooting Accuracy  Yellow Cards  Red Cards
0  England      5               45%             5          0
1   France      3               41%             6          0
2  Germany     10               52%             7          0


In [24]:
#in tất cả các cột, trừ 3 cột cuối
cols_exclude_3_last = euro12.iloc[:, :-3]
print("tất cả các cột trừ 3 cột cuối:")
print(cols_exclude_3_last.head(3))

tất cả các cột trừ 3 cột cuối:
      Team  Goals
0  England      5
1   France      3
2  Germany     10


In [25]:
# in các cột
selected_cols = ['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']
cols_10 = euro12[selected_cols]

print("Các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards:")
print(cols_10.head())

Các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards:
       Team  Goals Shooting Accuracy  Yellow Cards  Red Cards
0   England      5               45%             5          0
1    France      3               41%             6          0
2   Germany     10               52%             7          0
3     Italy      6               43%            16          0
4  Portugal      7               47%            12          0


In [26]:
#in các cột Team và Shooting Accuracy cho các đội 'England', 'Italy', 'Russia'.
target_teams = ['England', 'Italy', 'Russia']
mask_teams = euro12['Team'].isin(target_teams)
cols_11 = euro12[mask_teams][['Team', 'Shooting Accuracy']]
print("Các cột Team và Shooting Accuracy cho England, Italy, Russia:")
print(cols_11)

Các cột Team và Shooting Accuracy cho England, Italy, Russia:
      Team Shooting Accuracy
0  England               45%
3    Italy               43%
7   Russia               39%


# Bài 3.10

In [37]:
import pandas as pd
import numpy as np

data_drinks = {
    'country': ['Vietnam', 'Thailand', 'China', 'USA', 'Canada', 'Brazil', 'Germany', 'France', 'Uganda', 'Nigeria', 'Australia', 'New Zealand', 'UK', 'Spain'],
    'beer_servings': [111, 140, 150, 245, 120, 100, 275, 85, 30, 20, 261, 258, 200, 285],
    'spirit_servings': [2, 70, 80, 167, 100, 25, 145, 100, 1, 5, 220, 100, 150, 180],
    'wine_servings': [1, 5, 8, 80, 100, 50, 150, 220, 1, 1, 80, 175, 120, 250],
    'total_litres_of_pure_alcohol': [4.5, 6.0, 7.2, 10.4, 8.3, 7.5, 12.5, 10.0, 1.0, 1.5, 11.4, 10.8, 9.1, 11.0],
    'continent': ['Asia', 'Asia', 'Asia', 'North America', 'North America', 'South America', 'Europe', 'Europe', 'Africa', 'Africa', 'Oceania', 'Oceania', 'Europe', 'Europe']
}

drinks = pd.DataFrame(data_drinks).set_index('country')
print("DataFrame drinks mô phỏng đã được tạo.")

DataFrame drinks mô phỏng đã được tạo.


In [38]:
type(drinks)
drinks.shape

# Hiển thị tên các cột 
drinks.columns.tolist() 

# Xem 5 dòng dữ liệu đầu tiên và cuối cùng của drinks

drinks.head()
drinks.tail()

beer_servings  spirit_servings  wine_servings  \
country                                                      
Nigeria                 20                5              1   
Australia              261              220             80   
New Zealand            258              100            175   
UK                     200              150            120   
Spain                  285              180            250   

             total_litres_of_pure_alcohol continent  
country                                              
Nigeria                               1.5    Africa  
Australia                            11.4   Oceania  
New Zealand                          10.8   Oceania  
UK                                    9.1    Europe  
Spain                                11.0    Europe

In [39]:
print("lượng bia tiêu thụ trung bình ở mỗi châu lục ")
avg_beer_by_continent = drinks.groupby('continent')['beer_servings'].mean()
print(avg_beer_by_continent)

lượng bia tiêu thụ trung bình ở mỗi châu lục 
continent
Africa            25.000000
Asia             133.666667
Europe           211.250000
North America    182.500000
Oceania          259.500000
South America    100.000000
Name: beer_servings, dtype: float64


In [40]:
print("thống kê tổng quát rượu vang ở mỗi châu lục ")
wine_stats = drinks.groupby('continent')['wine_servings'].describe()
print(wine_stats)

thống kê tổng quát rượu vang ở mỗi châu lục 
               count        mean        std    min     25%    50%     75%  \
continent                                                                   
Africa           2.0    1.000000   0.000000    1.0    1.00    1.0    1.00   
Asia             3.0    4.666667   3.511885    1.0    3.00    5.0    6.50   
Europe           4.0  185.000000  60.277138  120.0  142.50  185.0  227.50   
North America    2.0   90.000000  14.142136   80.0   85.00   90.0   95.00   
Oceania          2.0  127.500000  67.175144   80.0  103.75  127.5  151.25   
South America    1.0   50.000000        NaN   50.0   50.00   50.0   50.00   

                 max  
continent             
Africa           1.0  
Asia             8.0  
Europe         250.0  
North America  100.0  
Oceania        175.0  
South America   50.0  


In [41]:
print("lượng bia, rượu mạnh, rượu vang tiêu thụ trung bình ở mỗi châu lục")
consumption_mean = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings']].mean()
print(consumption_mean)

lượng bia, rượu mạnh, rượu vang tiêu thụ trung bình ở mỗi châu lục
               beer_servings  spirit_servings  wine_servings
continent                                                   
Africa             25.000000         3.000000       1.000000
Asia              133.666667        50.666667       4.666667
Europe            211.250000       143.750000     185.000000
North America     182.500000       133.500000      90.000000
Oceania           259.500000       160.000000     127.500000
South America     100.000000        25.000000      50.000000


In [42]:
print("giá trị trung vị bia, rượu mạnh, rượu vang ở mỗi châu lục")
consumption_median = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings']].median()
print(consumption_median)

giá trị trung vị bia, rượu mạnh, rượu vang ở mỗi châu lục
               beer_servings  spirit_servings  wine_servings
continent                                                   
Africa                  25.0              3.0            1.0
Asia                   140.0             70.0            5.0
Europe                 237.5            147.5          185.0
North America          182.5            133.5           90.0
Oceania                259.5            160.0          127.5
South America          100.0             25.0           50.0


In [43]:
print("thống kê rượu mạnh ở mỗi châu lục ")
spirit_stats = drinks.groupby('continent')['spirit_servings'].agg(['mean', 'max', 'min'])
print(spirit_stats)

thống kê rượu mạnh ở mỗi châu lục 
                     mean  max  min
continent                          
Africa           3.000000    5    1
Asia            50.666667   80    2
Europe         143.750000  180  100
North America  133.500000  167  100
Oceania        160.000000  220  100
South America   25.000000   25   25


In [45]:
print("sắp xếp dữ liệu và Top/Bottom 5 ")

# sx DataFrame tăng dần theo cột beer_servings
drinks_sorted = drinks.sort_values(by='beer_servings', ascending=True)

# sx lại giảm dần hoặc lấy 5 dòng cuối của bảng đã sắp xếp tăng dần
top_5_beer = drinks_sorted.tail(5)[['beer_servings']]
print("quốc gia có lượng tiêu thụ bia nhiều nhất:")
print(top_5_beer.sort_values(by='beer_servings', ascending=False)) 

# lấy 5 dòng đầu của bảng đã sắp xếp tăng dần
bottom_5_beer = drinks_sorted.head(5)[['beer_servings']]
print("quốc gia có lượng tiêu thụ bia ít nhất:")
print(bottom_5_beer)

sắp xếp dữ liệu và Top/Bottom 5 
quốc gia có lượng tiêu thụ bia nhiều nhất:
             beer_servings
country                   
Spain                  285
Germany                275
Australia              261
New Zealand            258
USA                    245
quốc gia có lượng tiêu thụ bia ít nhất:
         beer_servings
country               
Nigeria             20
Uganda              30
France              85
Brazil             100
Vietnam            111


# Bài 3.11

In [28]:
import pandas as pd
import numpy as np

data_stocks1 = {
    'date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03'],
    'symbol': ['AAPL', 'GOOG', 'AAPL', 'GOOG', 'AAPL'],
    'open': [170.0, np.nan, 172.0, 96.0, 175.0], 
    'high': [171.0, 95.5, 172.5, 96.5, np.nan],
    'low': [169.5, 94.8, 171.5, 95.8, 174.5],
    'close': [170.5, 95.2, 172.2, 96.2, 175.2],
    'volume': [100000, 200000, 120000, 210000, 150000]
}

data_stocks2 = {
    'date': ['2023-01-03', '2023-01-04', '2023-01-04'],
    'symbol': ['GOOG', 'AAPL', 'GOOG'],
    'open': [97.0, 176.0, 98.0],
    'high': [97.5, 176.5, 98.5],
    'low': [96.8, 175.5, 97.8],
    'close': [97.2, 176.2, 98.2],
    'volume': [220000, 160000, 230000]
}

data_companies = {
    'symbol': ['AAPL', 'GOOG', 'MSFT'],
    'name': ['Apple Inc.', 'Alphabet Inc.', 'Microsoft Corp.'],
    'employees': [164000, 186000, 221000],
    'headquarters_city': ['Cupertino', 'Mountain View', 'Redmond'],
    'headquarters_state': ['CA', 'CA', 'WA']
}

stocks1 = pd.DataFrame(data_stocks1)
stocks2 = pd.DataFrame(data_stocks2)
companies = pd.DataFrame(data_companies)

stocks1['date'] = stocks1['date'].astype(str)
stocks2['date'] = stocks2['date'].astype(str)

In [29]:
stocks1.head()
stocks1.dtypes
stocks1.info()

stocks2.head()
stocks2.dtypes
stocks2.info()

companies
companies.dtypes
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    5 non-null      object 
 1   symbol  5 non-null      object 
 2   open    4 non-null      float64
 3   high    4 non-null      float64
 4   low     5 non-null      float64
 5   close   5 non-null      float64
 6   volume  5 non-null      int64  
dtypes: float64(4), int64(1), object(2)
memory usage: 412.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    3 non-null      object 
 1   symbol  3 non-null      object 
 2   open    3 non-null      float64
 3   high    3 non-null      float64
 4   low     3 non-null      float64
 5   close   3 non-null      float64
 6   volume  3 non-null      int64  
dtypes: float64(4), int64(1), object(2)
memory usage: 300.0+ bytes


In [30]:
# Kiểm tra dữ liệu Null (NaN)
stocks1.isnull().sum()

max_high_by_symbol = stocks1.groupby('symbol')['high'].transform('max')
min_low_by_symbol = stocks1.groupby('symbol')['low'].transform('min')

stocks1['open'] = stocks1['open'].fillna(max_high_by_symbol)

stocks1['low'] = stocks1['low'].fillna(min_low_by_symbol)

stocks1

date symbol   open   high    low  close  volume
0  2023-01-01   AAPL  170.0  171.0  169.5  170.5  100000
1  2023-01-01   GOOG   96.5   95.5   94.8   95.2  200000
2  2023-01-02   AAPL  172.0  172.5  171.5  172.2  120000
3  2023-01-02   GOOG   96.0   96.5   95.8   96.2  210000
4  2023-01-03   AAPL  175.0    NaN  174.5  175.2  150000

In [31]:
# Gộp stocks1 và stocks2 theo chiều dọc 
stocks = pd.concat([stocks1, stocks2], ignore_index=True)

# Xem 15 dòng dữ liệu cuối của stocks
stocks.tail(15)

date symbol   open   high    low  close  volume
0  2023-01-01   AAPL  170.0  171.0  169.5  170.5  100000
1  2023-01-01   GOOG   96.5   95.5   94.8   95.2  200000
2  2023-01-02   AAPL  172.0  172.5  171.5  172.2  120000
3  2023-01-02   GOOG   96.0   96.5   95.8   96.2  210000
4  2023-01-03   AAPL  175.0    NaN  174.5  175.2  150000
5  2023-01-03   GOOG   97.0   97.5   96.8   97.2  220000
6  2023-01-04   AAPL  176.0  176.5  175.5  176.2  160000
7  2023-01-04   GOOG   98.0   98.5   97.8   98.2  230000

In [32]:
# Gộp stocks và companies dựa trên cột 
stocks_companies = pd.merge(stocks, companies, on='symbol', how='left')

# Xem 5 dòng dữ liệu đầu của stocks_companies
stocks_companies.head()

date symbol   open   high    low  close  volume           name  \
0  2023-01-01   AAPL  170.0  171.0  169.5  170.5  100000     Apple Inc.   
1  2023-01-01   GOOG   96.5   95.5   94.8   95.2  200000  Alphabet Inc.   
2  2023-01-02   AAPL  172.0  172.5  171.5  172.2  120000     Apple Inc.   
3  2023-01-02   GOOG   96.0   96.5   95.8   96.2  210000  Alphabet Inc.   
4  2023-01-03   AAPL  175.0    NaN  174.5  175.2  150000     Apple Inc.   

   employees headquarters_city headquarters_state  
0     164000         Cupertino                 CA  
1     186000     Mountain View                 CA  
2     164000         Cupertino                 CA  
3     186000     Mountain View                 CA  
4     164000         Cupertino                 CA

In [33]:
# Chọn các cột cần tính toán
cols_to_avg = ['open', 'high', 'low', 'close', 'volume']

# Group theo 'symbol' và tính trung bình
company_averages = stocks_companies.groupby('symbol')[cols_to_avg].mean()
company_averages

open        high     low    close    volume
symbol                                                
AAPL    173.250  173.333333  172.75  173.525  132500.0
GOOG     96.875   97.000000   96.30   96.700  215000.0

In [34]:
# Group theo 'symbol' và sử dụng agg() để tính mean, max, min trên cột 'close'
close_stats = stocks_companies.groupby('symbol')['close'].agg(['mean', 'max', 'min'])
close_stats

mean    max    min
symbol                       
AAPL    173.525  176.2  170.5
GOOG     96.700   98.2   95.2

In [35]:
# Chuyển đổi cột 'date' sang kiểu DateTime
stocks_companies['parsed_time'] = pd.to_datetime(stocks_companies['date'])

# Cho biết kiểu dữ liệu của cột parsed_time
print(stocks_companies['parsed_time'].dtype) 

# Hiển thị 5 dòng dữ liệu đầu của stocks_companies
stocks_companies.head()

datetime64[ns]


date symbol   open   high    low  close  volume           name  \
0  2023-01-01   AAPL  170.0  171.0  169.5  170.5  100000     Apple Inc.   
1  2023-01-01   GOOG   96.5   95.5   94.8   95.2  200000  Alphabet Inc.   
2  2023-01-02   AAPL  172.0  172.5  171.5  172.2  120000     Apple Inc.   
3  2023-01-02   GOOG   96.0   96.5   95.8   96.2  210000  Alphabet Inc.   
4  2023-01-03   AAPL  175.0    NaN  174.5  175.2  150000     Apple Inc.   

   employees headquarters_city headquarters_state parsed_time  
0     164000         Cupertino                 CA  2023-01-01  
1     186000     Mountain View                 CA  2023-01-01  
2     164000         Cupertino                 CA  2023-01-02  
3     186000     Mountain View                 CA  2023-01-02  
4     164000         Cupertino                 CA  2023-01-03

In [36]:
# Áp dụng Boolean Masking và np.where để gán giá trị theo điều kiện:
stocks_companies['result'] = np.where(
    stocks_companies['close'] > stocks_companies['open'],
    'up',
    'down'
)

print(stocks_companies[['symbol', 'open', 'close', 'result']])

  symbol   open  close result
0   AAPL  170.0  170.5     up
1   GOOG   96.5   95.2   down
2   AAPL  172.0  172.2     up
3   GOOG   96.0   96.2     up
4   AAPL  175.0  175.2     up
5   GOOG   97.0   97.2     up
6   AAPL  176.0  176.2     up
7   GOOG   98.0   98.2     up


# Bài 2.12

In [1]:
import pandas as pd
import numpy as np
import datetime 

# Dữ liệu mẫu ratings
data_ratings = {
    'userId': [1, 1, 2, 2, 3, 3, 4, 4],
    'movieId': [1, 2, 1, 3, 2, 4, 1, 5],
    'rating': [5.0, 3.5, 4.0, 4.5, 5.0, 3.0, 4.0, 4.5],
    'timestamp': [1425941529, 1425942400, 1425942500, 1425942600, 1425942700, 1425942800, 1425942900, 1425943000]
}
ratings = pd.DataFrame(data_ratings)

# Dữ liệu mẫu movies
data_movies = {
    'movieId': [1, 2, 3, 4, 5],
    'title': ['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)', 'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)'],
    'genres': ['Adventure|Animation|Children|Comedy|Fantasy', 'Adventure|Children|Fantasy', 'Comedy|Romance', 'Comedy|Drama|Romance', 'Comedy']
}
movies = pd.DataFrame(data_movies)

print("Ratings info:", ratings.info())
print("Movies head:", movies.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   userId     8 non-null      int64  
 1   movieId    8 non-null      int64  
 2   rating     8 non-null      float64
 3   timestamp  8 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 388.0 bytes
Ratings info: None
Movies head:    movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy


In [2]:
#XỬ LÝ DL

# Thêm một dòng có rating thiếu để test
ratings.loc[len(ratings)] = [5, 6, np.nan, 1425943100]

# Tính trung bình rating cho việc điền giá trị
avg_rating = ratings['rating'].mean()

# Điền giá trị thiếu (fillna) bằng rating trung bình
ratings['rating'].fillna(avg_rating, inplace=True)

print("Ratings tail (sau khi điền NaN):", ratings.tail(2))

Ratings tail (sau khi điền NaN):    userId  movieId  rating     timestamp
7     4.0      5.0  4.5000  1.425943e+09
8     5.0      6.0  4.1875  1.425943e+09


C:\Users\Admin\AppData\Local\Temp\ipykernel_6628\1741947586.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ratings['rating'].fillna(avg_rating, inplace=True)


In [3]:
#GỘP DATAFRAME

# Gộp ratings và movies trên cột 'movieId'
movie_data = pd.merge(ratings, movies, on='movieId', how='left')
print(movie_data.head())


   userId  movieId  rating     timestamp                    title  \
0     1.0      1.0     5.0  1.425942e+09         Toy Story (1995)   
1     1.0      2.0     3.5  1.425942e+09           Jumanji (1995)   
2     2.0      1.0     4.0  1.425942e+09         Toy Story (1995)   
3     2.0      3.0     4.5  1.425943e+09  Grumpier Old Men (1995)   
4     3.0      2.0     5.0  1.425943e+09           Jumanji (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3                               Comedy|Romance  
4                   Adventure|Children|Fantasy  


In [4]:
#LỌC DỮ LIỆU THEO YÊU CẦU

# Lọc phim có rating >= 4.5
high_rated_movies = movie_data[movie_data['rating'] >= 4.5]
print(high_rated_movies[['title', 'rating']])

                                title  rating
0                    Toy Story (1995)     5.0
3             Grumpier Old Men (1995)     4.5
4                      Jumanji (1995)     5.0
7  Father of the Bride Part II (1995)     4.5


In [5]:
#THỐNG KÊ DỮ LIỆU

# Tính rating trung bình cho mỗi phim
avg_rating_per_movie = movie_data.groupby('title')['rating'].mean()
print(avg_rating_per_movie.sort_values(ascending=False).head())

title
Father of the Bride Part II (1995)    4.500000
Grumpier Old Men (1995)               4.500000
Toy Story (1995)                      4.333333
Jumanji (1995)                        4.250000
Waiting to Exhale (1995)              3.000000
Name: rating, dtype: float64


In [6]:
#PARSING TIMESTAMPS 

# Chuyển đổi cột 'timestamp' sang định dạng DateTime
movie_data['datetime'] = pd.to_datetime(movie_data['timestamp'], unit='s')
print("Kiểu dữ liệu mới:", movie_data['datetime'].dtype)
print("Kết quả:", movie_data[['timestamp', 'datetime']].head())

Kiểu dữ liệu mới: datetime64[ns]
Kết quả:       timestamp            datetime
0  1.425942e+09 2015-03-09 22:52:09
1  1.425942e+09 2015-03-09 23:06:40
2  1.425942e+09 2015-03-09 23:08:20
3  1.425943e+09 2015-03-09 23:10:00
4  1.425943e+09 2015-03-09 23:11:40
